//
//  MoviesRouter.swift
//  ArcMovies
//
//  Created by Jaime Costa Marques on 13/05/18.
//  Copyright (c) 2018 Jaime Costa Marques. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - MoviesRouterProtocol

/// _MoviesRouterProtocol_ is a protocol for router input behaviours
protocol MoviesRouterProtocol {
    
    var viewController: MoviesViewController? { get }
    
    /// Handles the navigation when selecting an movie in the list
    ///
    /// - parameter indexPath: The selected index path
    func navigateToMovie(atIndexPath indexPath: IndexPath)
}


// MARK: - MoviesRouter

/// _MoviesRouter_ is a class responsible for routing from _MoviesViewController_
final class MoviesRouter {
    
    weak var viewController: MoviesViewController?
    
    
    // MARK: - Initializers
    
    init(viewController: MoviesViewController) {
        
        self.viewController = viewController
    }
}

// MARK: - MoviesRouterProtocol

extension MoviesRouter: MoviesRouterProtocol {
    
    /// Handles the navigation when selecting an movie in the list to movie detail
    ///
    /// - parameter indexPath: The selected index path
    func navigateToMovie(atIndexPath indexPath: IndexPath) {
        
        let storyboard = UIStoryboard(name: "MovieDetails", bundle: nil)
        
        print(viewController?.output.movies, indexPath.row )
        
        // Instantiate MovieDetailsController
        guard let controller = storyboard.instantiateViewController(withIdentifier: "movieDetailsController") as? MovieDetailsViewController,
            let movies = viewController?.moviesViewModels, indexPath.row < movies.count
        else { return }
        
        controller.movie = movies[indexPath.row]
        controller.dominantColor = viewController?.movieTitle.textColor
        viewController?.navigationController?.pushViewController(controller, animated: true)
    }
}
