//
//  MoviesRouter.swift
//  ArcMovies
//
//  Created by Jaime Costa Marques on 13/05/18.
//  Copyright (c) 2018 Jaime Costa Marques. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - MoviesRouterProtocol

/// _MoviesRouterProtocol_ is a protocol for router input behaviours
protocol MoviesRouterProtocol {
    
    var viewController: MoviesViewController? { get }
    
    /// Handles the navigation when selecting an movie in the list
    ///
    /// - parameter indexPath: The selected index path
    func navigateToMovie(atIndexPath indexPath: IndexPath)
}


// MARK: - MoviesRouter

/// _MoviesRouter_ is a class responsible for routing from _MoviesViewController_
final class MoviesRouter {
    
    weak var viewController: MoviesViewController?
    
    
    // MARK: - Initializers
    
    init(viewController: MoviesViewController) {
        
        self.viewController = viewController
    }
}

// MARK: - MoviesRouterProtocol

extension MoviesRouter: MoviesRouterProtocol {
    
    /// Handles the navigation when selecting an movie in the list to movie detail
    ///
    /// - parameter indexPath: The selected index path
    func navigateToMovie(atIndexPath indexPath: IndexPath) {
        
//        if let movies = viewController?.output.movies, indexPath.row < movies.count {
//
//            let selectedMovie = movies[indexPath.row]
//
//            let movieViewController = MovieDetailsViewController(movie: selectedMovie)
//            viewController?.navigationController?.pushViewController(MovieDetailsViewController, animated: true)
//        }
    }
}
