//
//  MoviesWorker.swift
//  ArcMovies
//
//  Created by Jaime Costa Marques on 13/05/18.
//  Copyright (c) 2018 Jaime Costa Marques. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - MoviesWorker

/// _MoviesWorker_ is a worker object responsible to fetch movies from a store
class MoviesWorker {
    
    private var store: MoviesStoreProtocol
    
    
    // MARK: - Initializers
    
    /// Initializes an _MoviesWorker_ with a store
    ///
    /// - parameter store: A store where to fetch movies from (API, memory, etc)
    ///
    /// - returns: The instance of _MoviesWorker_
    init(store: MoviesStoreProtocol = MoviesStore()) {
        
        self.store = store
    }
    
    
    // MARK: - Business Logic
    
    /// Fetches movies from a store
    ///
    /// - parameter completion: The completion block
    func fetchMovies(completion: @escaping ([Movie]?, Error?) -> ()) {
        
        store.fetchMovies(completion: completion)
    }
}
